# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

format = """
[](fg:245) $directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$character"""

[directory]
style = "green bold"

[character]
success_symbol = "[➜](fg:245)"
error_symbol = "[➜](red)"
vimcmd_symbol = "[←](green)"

[git_branch]
format = "[$symbol $branch]($style) [($remote_name/$remote_branch)](fg:246)"
symbol = "󰊤"
style = "bright-blue"
always_show_remote = true

[git_status]
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
style = "yellow"
format = "[ [($conflicted$untracked$modified$staged$renamed$deleted)]($style)($ahead_behind)](bright-yellow) "

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "bright-black"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
